sudo: required

services:
  - docker

language: go

go:
  - 1.6

# before_install:

install:
  - docker build -t gameserver .
  - docker run -d -p 127.0.0.1:80:8080 --name gameserver1 gameserver

# before_script:

script:
  - docker ps | grep -q gameserver1

# after_success:

# after_failure:

before_deploy: # docker login?

deploy:
  skip_cleanup: true
  provider: script
  script: "./deploy.sh" # deploy to docker hub?
  on:
    branch: master

# later: multiple test branches?

# after_deploy:

# after_script:
